name             'git2consul'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures git2consul'
long_description 'Installs/Configures git2consul'
version          '0.1.0'
